### ISSUE TITLE
compiling failed under Android

### ISSUE THREAD

**Issue by 1797918430** [ugiacoman/react-native-broadcast#9]
error ：
:react-native-broadcast:generateDebugSources
:react-native-broadcast:compileDebugJavaWithJavacE:\reactNativeProject\yangJangApp\react_native-2.1\node_modules\react-native-broadcast\android\src\main\java\com\reactlibrary\RNBroadcastPackage.java:23: 错误: 方法不会覆盖或实现超类型的方法
    @Override
    ^
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: E:\reactNativeProject\yangJangApp\react_native-2.1\node_modules\react-native-broadcast\android\src\main\java\com\coremedia\iso\PropertyBoxParserImpl.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
1 个错误

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-broadcast:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 55s
 FAILED
244 actionable tasks: 26 executed, 218 up-to-date
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

**Comment by hollerith** [comment]
Same, fixing this issue you then get 

Note: Recompile with -Xlint:deprecation for details.                                                                           
D8: Cannot fit requested classes in a single dex file (# methods: 65611 > 65536)                                               
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:                                        
The number of method references in a .dex file cannot exceed 64K.                                                              
Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html                                  
        at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:131)                    
        at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:118)                    

### Assume this project is dead as issue is > 2 years old.
